development:
  adapter: postgresql
  encoding: unicode
  database: clean_blog_development
  pool: 5
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: clean_blog_test
  pool: 5
  min_messages: warning

production:
  adapter: postgresql
  encoding: unicode
  database: clean_blog_production
  pool: 5
  min_messages: warning